version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "944443936935"
    AWS_DEFAULT_REGION: "eu-north-1"
    IMAGE_REPO_NAME: "brain-tasks-app"
    CLUSTER_NAME: "brain-tasks-cluster"
    REPOSITORY_URI: "944443936935.dkr.ecr.eu-north-1.amazonaws.com/brain-tasks-app"

phases:
  install:
    commands:
      - echo "Installing kubectl and eksctl..."
      - curl -sSLo kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin/
  
  pre_build:
    commands:
      - echo "Checking if EKS cluster exists..."
      - | 
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Updating Kubeconfig..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME
      - echo "Updating deployment manifest with image tag $IMAGE_TAG..."
      - sed -i "s|CONTAINER_IMAGE|$REPOSITORY_URI:$IMAGE_TAG|g" deployment.yaml
      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - echo "Automation Complete."